### ISSUE TITLE
Address not getting converted correctly through speeech

### ISSUE THREAD

**Issue by tusharIndore** [awslabs/aws-lex-web-ui#13] opened 2017-11-20 10:33 UTC
When I am feeding address through speech ,address speech to text conversion not occurring  correctly ,Why ?
Is it possible to integrate amazon lex with google speech to text api or any third party api for the above task.

**Comment by atoa** [comment] 2017-11-20 15:13
Not sure if you are using built-in slots to capture the address. I suggest you look into the [built-in slot types](http://docs.aws.amazon.com/lex/latest/dg/howitworks-builtins-slots.html) including the [Slot Type Reference](https://developer.amazon.com/docs/custom-skills/slot-type-reference.html) in the Alexa Skills Kit documentation. You can integrate third-party APIs in the backend using a [Lambda Function](http://docs.aws.amazon.com/lex/latest/dg/using-lambda.html).

I am closing this issue since it seems like the question is more related to the Amazon Lex service itself rather than the web UI provided by this project. You may want to instead try the [Amazon Lex Discussion Forum](https://forums.aws.amazon.com/forum.jspa?forumID=251). Feel free to reopen if you feel that the issue is specific to this project.

-- Oliver

**Closed by atoa** 2017-11-20 15:13 UTC
Labels: question

**Comment by tusharIndore** [comment] 2017-11-21 06:41
Hi Oliver,

Thanks for your reply.
I think for above problem we can use third party api (google speech api) for correct address translation. 
For address translation  and for all speech to text translation , I want to use  third party api such as google speech api then after getting correct address in text form I want to send text address to amazon lex by using same lex web UI interface. How this can be incorporated in your existing logic.
If this is possible please share code for it.

Regards,
Tushar Choudhary
